"""The wire protocol as pure functions and value objects.

Nothing in this package performs I/O. The constants and enumerations come from
``_defs``, which is generated from ``protocol/definition.toml`` at the root of
the repository and must not be edited by hand.
"""

from __future__ import annotations

from s3_power_profiler.protocol import commands
from s3_power_profiler.protocol._defs import (
    BLOCK_SAMPLES,
    CAL_TARGET_DAC,
    COMMAND_MAX_PAYLOAD,
    FRAME_MAX_PAYLOAD,
    PROTOCOL_VERSION,
    RANGE_AUTO,
    RANGE_COUNT,
    SAMPLE_ADC_MASK,
    SAMPLE_ADC_SHIFT,
    SAMPLE_FAULT_MASK,
    SAMPLE_FAULT_SHIFT,
    SAMPLE_INVALID_MASK,
    SAMPLE_INVALID_SHIFT,
    SAMPLE_LOGIC_MASK,
    SAMPLE_LOGIC_SHIFT,
    SAMPLE_RANGE_MASK,
    SAMPLE_RANGE_SHIFT,
    Command,
    DeviceState,
    Event,
    Fault,
    FrameType,
    Mode,
    Status,
)
from s3_power_profiler.protocol.commands import (
    CommandMessage,
    DeviceInfo,
    DeviceStatus,
    EventMessage,
    ResponseMessage,
    decode_command,
    decode_event,
    decode_response,
    encode_command,
    encode_event,
    encode_response,
)
from s3_power_profiler.protocol.crc import crc16
from s3_power_profiler.protocol.frame import SEQUENCE_MODULO, Frame, FrameDecoder, encode_frame
from s3_power_profiler.protocol.sample import (
    SAMPLE_WORD_SIZE,
    Sample,
    SampleColumns,
    pack_sample,
    pack_words,
    split_words,
    unpack_sample,
    unpack_words,
)
from s3_power_profiler.protocol.stream import (
    INDEX_MODULO,
    MAX_STREAM_SAMPLES,
    StreamPayload,
    decode_stream_payload,
    encode_stream_payload,
)

__all__ = [
    "BLOCK_SAMPLES",
    "CAL_TARGET_DAC",
    "COMMAND_MAX_PAYLOAD",
    "FRAME_MAX_PAYLOAD",
    "INDEX_MODULO",
    "MAX_STREAM_SAMPLES",
    "PROTOCOL_VERSION",
    "RANGE_AUTO",
    "RANGE_COUNT",
    "SAMPLE_ADC_MASK",
    "SAMPLE_ADC_SHIFT",
    "SAMPLE_FAULT_MASK",
    "SAMPLE_FAULT_SHIFT",
    "SAMPLE_INVALID_MASK",
    "SAMPLE_INVALID_SHIFT",
    "SAMPLE_LOGIC_MASK",
    "SAMPLE_LOGIC_SHIFT",
    "SAMPLE_RANGE_MASK",
    "SAMPLE_RANGE_SHIFT",
    "SAMPLE_WORD_SIZE",
    "SEQUENCE_MODULO",
    "Command",
    "CommandMessage",
    "DeviceInfo",
    "DeviceState",
    "DeviceStatus",
    "Event",
    "EventMessage",
    "Fault",
    "Frame",
    "FrameDecoder",
    "FrameType",
    "Mode",
    "ResponseMessage",
    "Sample",
    "SampleColumns",
    "Status",
    "StreamPayload",
    "commands",
    "crc16",
    "decode_command",
    "decode_event",
    "decode_response",
    "decode_stream_payload",
    "encode_command",
    "encode_event",
    "encode_frame",
    "encode_response",
    "encode_stream_payload",
    "pack_sample",
    "pack_words",
    "split_words",
    "unpack_sample",
    "unpack_words",
]
