"""Wire protocol constants.

Generated by protocol/generate.py from protocol/definition.toml. Do not edit.
"""

from __future__ import annotations

import enum

PROTOCOL_VERSION = 1

FRAME_MAGIC = 0xA55A
FRAME_HEADER_SIZE = 8
FRAME_CRC_SIZE = 2
FRAME_MAX_PAYLOAD = 2048
COMMAND_MAX_PAYLOAD = 256
BLOCK_SAMPLES = 256

CRC16_POLYNOMIAL = 0x1021
CRC16_INIT = 0xFFFF
CRC16_CHECK = 0x29B1


class FrameType(enum.IntEnum):
    STREAM = 0x01
    COMMAND = 0x02
    RESPONSE = 0x03
    EVENT = 0x04


class Command(enum.IntEnum):
    GET_INFO = 0x01
    GET_STATUS = 0x02
    SET_MODE = 0x10
    SET_VOLTAGE = 0x11
    DUT_POWER = 0x12
    SET_RANGE = 0x13
    SET_DOWN_N = 0x14
    START = 0x20
    STOP = 0x21
    CAL_ZERO = 0x30
    CAL_WRITE = 0x31
    CLEAR_FAULT = 0x40


class Status(enum.IntEnum):
    OK = 0x00
    BAD_ARGUMENT = 0x01
    WRONG_STATE = 0x02
    FAULT_ACTIVE = 0x03
    BUSY = 0x04
    UNKNOWN_COMMAND = 0x05


class Event(enum.IntEnum):
    FAULT_RAISED = 0x01
    POWER_BUDGET_CHANGED = 0x02
    STATE_CHANGED = 0x03


class DeviceState(enum.IntEnum):
    BOOT = 0x00
    SELFTEST = 0x01
    IDLE = 0x02
    ARMED = 0x03
    STREAMING = 0x04
    FAULT = 0x05


class Mode(enum.IntEnum):
    AMPERE_METER = 0x00
    SOURCE_METER = 0x01


class Fault(enum.IntFlag):
    """Bits of the 16-bit fault flags."""

    OVERCURRENT = 1 << 0
    POWER_LIMIT = 1 << 1
    THERMAL = 1 << 2
    SELFTEST = 1 << 3


# Sample word fields: shift, then mask of the shifted-down value.
SAMPLE_ADC_SHIFT = 0
SAMPLE_ADC_MASK = 0xFFFF
SAMPLE_RANGE_SHIFT = 16
SAMPLE_RANGE_MASK = 0x03
SAMPLE_INVALID_SHIFT = 18
SAMPLE_INVALID_MASK = 0x01
SAMPLE_FAULT_SHIFT = 19
SAMPLE_FAULT_MASK = 0x01
SAMPLE_RESERVED_SHIFT = 20
SAMPLE_RESERVED_MASK = 0x0F
SAMPLE_LOGIC_SHIFT = 24
SAMPLE_LOGIC_MASK = 0xFF

RANGE_COUNT = 0x04
RANGE_AUTO = 0xFF
CAL_TARGET_DAC = 0x10
