#!/usr/bin/env python3
"""Generate the protocol bindings and test vectors.

The protocol constants live in ``definition.toml`` and the inputs of the test
vectors in ``vectors.toml``. This script turns them into a C header and a
Python module with the constants, and into a JSON file and a C header with
the encoded vectors.

Usage:
    python protocol/generate.py          write the generated files
    python protocol/generate.py --check  exit with status 1 if a file is stale

Requires Python 3.11 or later and nothing outside the standard library.
"""

from __future__ import annotations

import argparse
import binascii
import json
import struct
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DEFINITION = ROOT / "protocol" / "definition.toml"
VECTORS = ROOT / "protocol" / "vectors.toml"

C_DEFS = ROOT / "firmware/components/proto/include/proto/pp_proto_defs.h"
C_VECTORS = ROOT / "firmware/test/host/generated/pp_proto_vectors.h"
PY_DEFS = ROOT / "host/src/s3_power_profiler/protocol/_defs.py"
JSON_VECTORS = ROOT / "protocol/vectors.json"

NOTICE = "Generated by protocol/generate.py from protocol/definition.toml. Do not edit."

# (definition table, C enum type, C prefix, Python class, Python base)
ENUMS = [
    ("frame_types", "pp_frame_type_t", "PP_FRAME_TYPE_", "FrameType", "IntEnum"),
    ("commands", "pp_command_id_t", "PP_CMD_", "Command", "IntEnum"),
    ("status", "pp_proto_status_t", "PP_PROTO_STATUS_", "Status", "IntEnum"),
    ("events", "pp_event_id_t", "PP_EVENT_", "Event", "IntEnum"),
    ("states", "pp_device_state_t", "PP_STATE_", "DeviceState", "IntEnum"),
    ("modes", "pp_mode_t", "PP_MODE_", "Mode", "IntEnum"),
]


# --- Reference encoder -----------------------------------------------------


def crc16(data: bytes, polynomial: int, init: int) -> int:
    """Bitwise CRC-16, most significant bit first, without reflection."""
    crc = init
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ polynomial) if crc & 0x8000 else (crc << 1)
            crc &= 0xFFFF
    return crc


def encode_frame(spec: dict[str, Any], frame_type: int, sequence: int, payload: bytes) -> bytes:
    """Build a complete frame: header, payload and CRC."""
    proto, crc = spec["protocol"], spec["crc"]
    if len(payload) > proto["max_payload"]:
        raise ValueError(f"payload of {len(payload)} bytes exceeds max_payload")
    body = struct.pack("<HBBHH", proto["magic"], frame_type, 0, len(payload), sequence) + payload
    return body + struct.pack("<H", crc16(body, crc["polynomial"], crc["init"]))


def pack_sample(spec: dict[str, Any], sample: dict[str, int]) -> int:
    """Pack the fields of a sample into its 32-bit word."""
    word = 0
    for name, (lsb, width) in spec["sample_word"].items():
        value = sample.get(name, 0)
        if not 0 <= value < (1 << width):
            raise ValueError(f"sample field {name}={value} does not fit in {width} bits")
        word |= value << lsb
    return word


# --- Validation ------------------------------------------------------------


def validate(spec: dict[str, Any]) -> None:
    """Reject a definition that contradicts itself."""
    proto, crc = spec["protocol"], spec["crc"]
    header = struct.calcsize("<HBBHH")
    if proto["header_size"] != header:
        raise ValueError(f"header_size must be {header}")
    if crc["polynomial"] == 0x1021:
        # Independent implementation from the standard library.
        probe = b"123456789"
        if binascii.crc_hqx(probe, crc["init"]) != crc16(probe, crc["polynomial"], crc["init"]):
            raise ValueError("reference CRC disagrees with binascii.crc_hqx")
    if crc16(b"123456789", crc["polynomial"], crc["init"]) != crc["check"]:
        raise ValueError("crc.check does not match the CRC parameters")
    for table, *_ in ENUMS:
        values = list(spec[table].values())
        if len(values) != len(set(values)):
            raise ValueError(f"duplicate value in [{table}]")
    bits = sorted((lsb, width) for lsb, width in spec["sample_word"].values())
    position = 0
    for lsb, width in bits:
        if lsb != position:
            raise ValueError("sample_word fields must be contiguous and not overlap")
        position += width
    if position != 32:
        raise ValueError("sample_word fields must add up to 32 bits")
    stream_payload = 8 + 4 * proto["block_samples"]
    if stream_payload > proto["max_payload"]:
        raise ValueError("a full stream frame does not fit in max_payload")


# --- Vectors ---------------------------------------------------------------


def build_vectors(spec: dict[str, Any], source: dict[str, Any]) -> dict[str, Any]:
    """Encode every vector input with the reference implementation."""
    crc = spec["crc"]
    crcs = [
        {
            "name": item["name"],
            "data": item["data"].lower(),
            "crc": crc16(bytes.fromhex(item["data"]), crc["polynomial"], crc["init"]),
        }
        for item in source.get("crc", [])
    ]
    frames = []
    for item in source.get("frame", []):
        payload = bytes.fromhex(item["payload"])
        frame_type = spec["frame_types"][item["type"]]
        frames.append(
            {
                "name": item["name"],
                "type": frame_type,
                "sequence": item["sequence"],
                "payload": payload.hex(),
                "frame": encode_frame(spec, frame_type, item["sequence"], payload).hex(),
            }
        )
    samples = []
    for item in source.get("sample", []):
        fields = {name: item.get(name, 0) for name in spec["sample_word"]}
        samples.append({"name": item["name"], **fields, "word": pack_sample(spec, fields)})
    names = [v["name"] for group in (crcs, frames, samples) for v in group]
    if len(names) != len(set(names)):
        raise ValueError("vector names must be unique")
    return {
        "protocol_version": spec["protocol"]["version"],
        "crc": crcs,
        "frames": frames,
        "samples": samples,
    }


# --- Renderers -------------------------------------------------------------


def hex_literal(value: int, digits: int = 2) -> str:
    """Format a number as an uppercase hexadecimal literal."""
    return f"0x{value:0{digits}X}"


def render_c_defs(spec: dict[str, Any]) -> str:
    """Render the C header with the protocol constants."""
    proto, crc = spec["protocol"], spec["crc"]
    out = [
        "/*",
        " * Wire protocol constants.",
        f" * {NOTICE}",
        " */",
        "#ifndef PP_PROTO_DEFS_H",
        "#define PP_PROTO_DEFS_H",
        "",
        f"#define PP_PROTO_VERSION {proto['version']}u",
        "",
        f"#define PP_FRAME_MAGIC {hex_literal(proto['magic'], 4)}u",
        f"#define PP_FRAME_HEADER_SIZE {proto['header_size']}u",
        f"#define PP_FRAME_CRC_SIZE {proto['crc_size']}u",
        f"#define PP_FRAME_MAX_PAYLOAD {proto['max_payload']}u",
        f"#define PP_COMMAND_MAX_PAYLOAD {proto['max_command_payload']}u",
        f"#define PP_BLOCK_SAMPLES {proto['block_samples']}u",
        "",
        f"#define PP_CRC16_POLYNOMIAL {hex_literal(crc['polynomial'], 4)}u",
        f"#define PP_CRC16_INIT {hex_literal(crc['init'], 4)}u",
        f"#define PP_CRC16_CHECK {hex_literal(crc['check'], 4)}u",
        "",
    ]
    for table, c_type, prefix, _py_class, _py_base in ENUMS:
        out.append("typedef enum {")
        out.extend(
            f"    {prefix}{name} = {hex_literal(value)}," for name, value in spec[table].items()
        )
        out.append(f"}} {c_type};")
        out.append("")
    out.append("/* Bits of the 16-bit fault flags. */")
    out.extend(f"#define PP_FAULT_{name} (1u << {bit})" for name, bit in spec["faults"].items())
    out.append("")
    out.append("/* Sample word fields: shift, then mask of the shifted-down value. */")
    for name, (lsb, width) in spec["sample_word"].items():
        upper = name.upper()
        out.append(f"#define PP_SAMPLE_{upper}_SHIFT {lsb}u")
        out.append(f"#define PP_SAMPLE_{upper}_MASK {hex_literal((1 << width) - 1)}u")
    out.append("")
    out.extend(
        f"#define PP_{name} {hex_literal(value)}u" for name, value in spec["constants"].items()
    )
    out.extend(["", "#endif /* PP_PROTO_DEFS_H */", ""])
    return "\n".join(out)


def render_py_defs(spec: dict[str, Any]) -> str:
    """Render the Python module with the protocol constants."""
    proto, crc = spec["protocol"], spec["crc"]
    out = [
        '"""Wire protocol constants.',
        "",
        f"{NOTICE}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import enum",
        "",
        f"PROTOCOL_VERSION = {proto['version']}",
        "",
        f"FRAME_MAGIC = {hex_literal(proto['magic'], 4)}",
        f"FRAME_HEADER_SIZE = {proto['header_size']}",
        f"FRAME_CRC_SIZE = {proto['crc_size']}",
        f"FRAME_MAX_PAYLOAD = {proto['max_payload']}",
        f"COMMAND_MAX_PAYLOAD = {proto['max_command_payload']}",
        f"BLOCK_SAMPLES = {proto['block_samples']}",
        "",
        f"CRC16_POLYNOMIAL = {hex_literal(crc['polynomial'], 4)}",
        f"CRC16_INIT = {hex_literal(crc['init'], 4)}",
        f"CRC16_CHECK = {hex_literal(crc['check'], 4)}",
        "",
    ]
    for table, _c_type, _prefix, py_class, py_base in ENUMS:
        out.extend(["", f"class {py_class}(enum.{py_base}):"])
        out.extend(f"    {name} = {hex_literal(value)}" for name, value in spec[table].items())
        out.append("")
    out.extend(["", "class Fault(enum.IntFlag):", '    """Bits of the 16-bit fault flags."""', ""])
    out.extend(f"    {name} = 1 << {bit}" for name, bit in spec["faults"].items())
    out.extend(["", "", "# Sample word fields: shift, then mask of the shifted-down value."])
    for name, (lsb, width) in spec["sample_word"].items():
        upper = name.upper()
        out.append(f"SAMPLE_{upper}_SHIFT = {lsb}")
        out.append(f"SAMPLE_{upper}_MASK = {hex_literal((1 << width) - 1)}")
    out.append("")
    out.extend(f"{name} = {hex_literal(value)}" for name, value in spec["constants"].items())
    out.append("")
    return "\n".join(out)


def c_bytes(data: bytes) -> str:
    """C initializer for a byte array. An empty array gets one unused byte."""
    values = data if data else b"\x00"
    lines = []
    for start in range(0, len(values), 12):
        chunk = values[start : start + 12]
        lines.append("    " + ", ".join(hex_literal(b) for b in chunk) + ",")
    return "\n".join(lines)


def render_c_vectors(vectors: dict[str, Any]) -> str:
    """Render the C header with the encoded test vectors."""
    out = [
        "/*",
        " * Shared protocol test vectors.",
        " * Generated by protocol/generate.py from protocol/vectors.toml. Do not edit.",
        " */",
        "#ifndef PP_PROTO_VECTORS_H",
        "#define PP_PROTO_VECTORS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    const uint8_t *data;",
        "    size_t data_len;",
        "    uint16_t crc;",
        "} pp_crc_vector_t;",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t type;",
        "    uint16_t sequence;",
        "    const uint8_t *payload;",
        "    size_t payload_len;",
        "    const uint8_t *frame;",
        "    size_t frame_len;",
        "} pp_frame_vector_t;",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint16_t adc;",
        "    uint8_t range;",
        "    uint8_t invalid;",
        "    uint8_t fault;",
        "    uint8_t logic;",
        "    uint32_t word;",
        "} pp_sample_vector_t;",
        "",
    ]
    for item in vectors["crc"]:
        out.append(f"static const uint8_t pp_vec_crc_{item['name']}_data[] = {{")
        out.append(c_bytes(bytes.fromhex(item["data"])))
        out.append("};")
    out.extend(["", "static const pp_crc_vector_t pp_crc_vectors[] = {"])
    for item in vectors["crc"]:
        length = len(bytes.fromhex(item["data"]))
        out.append(
            f'    {{"{item["name"]}", pp_vec_crc_{item["name"]}_data, {length}u, '
            f"{hex_literal(item['crc'], 4)}u}},"
        )
    out.extend(["};", ""])
    for item in vectors["frames"]:
        for part in ("payload", "frame"):
            out.append(f"static const uint8_t pp_vec_frame_{item['name']}_{part}[] = {{")
            out.append(c_bytes(bytes.fromhex(item[part])))
            out.append("};")
    out.extend(["", "static const pp_frame_vector_t pp_frame_vectors[] = {"])
    for item in vectors["frames"]:
        name = item["name"]
        out.append("    {")
        out.append(f'        "{name}",')
        out.append(f"        {hex_literal(item['type'])}u,")
        out.append(f"        {hex_literal(item['sequence'], 4)}u,")
        out.append(f"        pp_vec_frame_{name}_payload,")
        out.append(f"        {len(bytes.fromhex(item['payload']))}u,")
        out.append(f"        pp_vec_frame_{name}_frame,")
        out.append(f"        {len(bytes.fromhex(item['frame']))}u,")
        out.append("    },")
    out.extend(["};", "", "static const pp_sample_vector_t pp_sample_vectors[] = {"])
    out.extend(
        f'    {{"{item["name"]}", {hex_literal(item["adc"], 4)}u, {item["range"]}u, '
        f"{item['invalid']}u, {item['fault']}u, {hex_literal(item['logic'])}u, "
        f"{hex_literal(item['word'], 8)}u}},"
        for item in vectors["samples"]
    )
    out.extend(["};", ""])
    for kind in ("crc", "frame", "sample"):
        array = f"pp_{kind}_vectors"
        out.append(f"#define PP_{kind.upper()}_VECTOR_COUNT (sizeof({array}) / sizeof({array}[0]))")
    out.extend(["", "#endif /* PP_PROTO_VECTORS_H */", ""])
    return "\n".join(out)


def render_json_vectors(vectors: dict[str, Any]) -> str:
    """Render the JSON file with the encoded test vectors."""
    return json.dumps(vectors, indent=2) + "\n"


# --- Entry point -----------------------------------------------------------


def generate() -> dict[Path, str]:
    """Return the content of every generated file, keyed by its path."""
    with DEFINITION.open("rb") as handle:
        spec = tomllib.load(handle)
    with VECTORS.open("rb") as handle:
        source = tomllib.load(handle)
    validate(spec)
    vectors = build_vectors(spec, source)
    return {
        C_DEFS: render_c_defs(spec),
        PY_DEFS: render_py_defs(spec),
        C_VECTORS: render_c_vectors(vectors),
        JSON_VECTORS: render_json_vectors(vectors),
    }


def main(argv: list[str] | None = None) -> int:
    """Write the generated files, or report the stale ones with ``--check``."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit with status 1 if a generated file is stale",
    )
    args = parser.parse_args(argv)

    stale = []
    for path, content in generate().items():
        current = path.read_bytes().decode("utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content.encode("utf-8"))
            print(f"wrote {path.relative_to(ROOT).as_posix()}")

    if args.check and stale:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT).as_posix()}", file=sys.stderr)
        print("Run `python protocol/generate.py` and commit the result.", file=sys.stderr)
        return 1
    if not stale:
        print("generated files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
