/*
 * Wire protocol constants.
 * Generated by protocol/generate.py from protocol/definition.toml. Do not edit.
 */
#ifndef PP_PROTO_DEFS_H
#define PP_PROTO_DEFS_H

#define PP_PROTO_VERSION 1u

#define PP_FRAME_MAGIC 0xA55Au
#define PP_FRAME_HEADER_SIZE 8u
#define PP_FRAME_CRC_SIZE 2u
#define PP_FRAME_MAX_PAYLOAD 2048u
#define PP_COMMAND_MAX_PAYLOAD 256u
#define PP_BLOCK_SAMPLES 256u

#define PP_CRC16_POLYNOMIAL 0x1021u
#define PP_CRC16_INIT 0xFFFFu
#define PP_CRC16_CHECK 0x29B1u

typedef enum {
    PP_FRAME_TYPE_STREAM = 0x01,
    PP_FRAME_TYPE_COMMAND = 0x02,
    PP_FRAME_TYPE_RESPONSE = 0x03,
    PP_FRAME_TYPE_EVENT = 0x04,
} pp_frame_type_t;

typedef enum {
    PP_CMD_GET_INFO = 0x01,
    PP_CMD_GET_STATUS = 0x02,
    PP_CMD_SET_MODE = 0x10,
    PP_CMD_SET_VOLTAGE = 0x11,
    PP_CMD_DUT_POWER = 0x12,
    PP_CMD_SET_RANGE = 0x13,
    PP_CMD_SET_DOWN_N = 0x14,
    PP_CMD_START = 0x20,
    PP_CMD_STOP = 0x21,
    PP_CMD_CAL_ZERO = 0x30,
    PP_CMD_CAL_WRITE = 0x31,
    PP_CMD_CLEAR_FAULT = 0x40,
} pp_command_id_t;

typedef enum {
    PP_PROTO_STATUS_OK = 0x00,
    PP_PROTO_STATUS_BAD_ARGUMENT = 0x01,
    PP_PROTO_STATUS_WRONG_STATE = 0x02,
    PP_PROTO_STATUS_FAULT_ACTIVE = 0x03,
    PP_PROTO_STATUS_BUSY = 0x04,
    PP_PROTO_STATUS_UNKNOWN_COMMAND = 0x05,
} pp_proto_status_t;

typedef enum {
    PP_EVENT_FAULT_RAISED = 0x01,
    PP_EVENT_POWER_BUDGET_CHANGED = 0x02,
    PP_EVENT_STATE_CHANGED = 0x03,
} pp_event_id_t;

typedef enum {
    PP_STATE_BOOT = 0x00,
    PP_STATE_SELFTEST = 0x01,
    PP_STATE_IDLE = 0x02,
    PP_STATE_ARMED = 0x03,
    PP_STATE_STREAMING = 0x04,
    PP_STATE_FAULT = 0x05,
} pp_device_state_t;

typedef enum {
    PP_MODE_AMPERE_METER = 0x00,
    PP_MODE_SOURCE_METER = 0x01,
} pp_mode_t;

/* Bits of the 16-bit fault flags. */
#define PP_FAULT_OVERCURRENT (1u << 0)
#define PP_FAULT_POWER_LIMIT (1u << 1)
#define PP_FAULT_THERMAL (1u << 2)
#define PP_FAULT_SELFTEST (1u << 3)

/* Sample word fields: shift, then mask of the shifted-down value. */
#define PP_SAMPLE_ADC_SHIFT 0u
#define PP_SAMPLE_ADC_MASK 0xFFFFu
#define PP_SAMPLE_RANGE_SHIFT 16u
#define PP_SAMPLE_RANGE_MASK 0x03u
#define PP_SAMPLE_INVALID_SHIFT 18u
#define PP_SAMPLE_INVALID_MASK 0x01u
#define PP_SAMPLE_FAULT_SHIFT 19u
#define PP_SAMPLE_FAULT_MASK 0x01u
#define PP_SAMPLE_RESERVED_SHIFT 20u
#define PP_SAMPLE_RESERVED_MASK 0x0Fu
#define PP_SAMPLE_LOGIC_SHIFT 24u
#define PP_SAMPLE_LOGIC_MASK 0xFFu

#define PP_RANGE_COUNT 0x04u
#define PP_RANGE_AUTO 0xFFu
#define PP_CAL_TARGET_DAC 0x10u

#endif /* PP_PROTO_DEFS_H */
